openapi: 3.0.0
info:
  title: Command Executor API
  version: 1.0.0
servers:
  - url: https://wblo235iab.execute-api.eu-north-1.amazonaws.com/prod
paths:
  /command:
    post:
      summary: Execute a command
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - command
              properties:
                command:
                  type: string
                  example: echo Hello, world!
      responses:
        200:
          description: Command executed
          content:
            application/json:
              schema:
                type: object
                properties:
                  type:
                    type: string
                    example: stdout
                  message:
                    type: string
                    example: Hello, world!\n
